export enum ParticipationStatus {
  PENDING = 'PENDING',
  WON = 'WON',
  LOST = 'LOST',
  APPROVED = 'APPROVED',
  CONFIRMED = 'CONFIRMED',
  VERIFIED = 'VERIFIED',
  PROCESSING = 'PROCESSING',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED',
}
